// Generated by CoffeeScript 1.4.0
(function() {
  var MainPageTitle, app, elasticSearchHost, elasticSearchPort, elasticSearchUrl, errorLogger, express, hbs, http, indexName, logger, wikijs;

  MainPageTitle = "Hlavná stránka";

  elasticSearchHost = "localhost";

  elasticSearchPort = "9200";

  indexName = "wikipedia_cached";

  express = require('express');

  http = require('http');

  wikijs = require('wiky.js');

  app = express();

  hbs = require('hbs');

  http.globalAgent.maxSockets = 1000;

  elasticSearchUrl = function(title) {
    return ("http://" + elasticSearchHost + ":" + elasticSearchPort + "/" + indexName + "/page/") + encodeURIComponent(title);
  };

  logger = function(req, res, next) {
    console.log('Request: ' + req.method + ' ' + req.url);
    return next();
  };

  errorLogger = function(err, req, res, next) {
    console.log('Error: ' + req.method + ' ' + req.url + ' ' + err.message);
    return next();
  };

  app.configure(function() {
    app.set('view engine', 'hbs');
    app.engine('hbs', hbs.__express);
    app.use(logger);
    app.use(app.router);
    return app.use(express["static"]('public'));
  });

  app.get('/', function(req, res) {
    return res.redirect('/wiki/' + MainPageTitle);
  });

  app.get('/wiki', function(req, res) {
    return res.redirect('/wiki/' + MainPageTitle);
  });

  app.get('/wiki/:contentId', function(req, res) {
    return http.get(elasticSearchUrl(req.params.contentId), function(innerRes) {
      var body;
      if (innerRes.statusCode !== 200) {
        res.send(innerRes.statusCode);
        return innerRes.resume();
      } else {
        body = '';
        innerRes.on('data', function(bodyChunk) {
          return body += bodyChunk;
        });
        return innerRes.on('end', function() {
          return res.render('page', {
            'title': req.params.contentId,
            'content': JSON.parse(body)._source.html
          });
        });
      }
    }).on('error', function(e) {
      return console.log('Got error: ' + e.message);
    });
  });

  app.get('/search/:searchString', function(req, res) {
    return res.send(req.params.searchString);
  });

  app.listen(8080);

}).call(this);
